COUNTRIES_LIST = [
    # "Portugal",
    # "Spain",
    # "France",
    "United Kingdom",
    # "Ireland",
    # "Norway",
    # "Sweden",
    # "Finland",
    # "Denmark",
    "Germany",
    # "Belgium",
    # "Netherlands",
    # "Poland",
    # "Italy",
    # "Austria",
    # "Hungary",
    # "Bulgaria",
    # "Greece",
    # "Romania",
    # "Estonia",
    # "Latvia",
    # "Lithuania",
    # "Czechia",
    # "Slovakia",
    # "Croatia",
    # "Switzerland",
]

SKILLS_LIST = [
    "sql",
    "nosql",
    "mysql",
    "PL/SQL",
    "postgres",
    "PostgreSQL",
    "no-SQL",
    "snowflake",
    "Databricks",
    "Terraform",
    "airflow",
    "datafactory",
    "prefect",
    "luigi",
    "glue",
    "Java",
    "dbt",
    "Python",
    "Pytorch",
    "DAX",
    "Bash",
    "Shell",
    "aws",
    "azure",
    "gcp",
    "Tensorflow",
    "C#",
    "Redshift",
    "BigQuery",
    "Pyspark",
    "S3",
    "Spark",
    "Scala",
    "athena",
    "GraphQL",
    "API",
    "Streamlit",
    "Plotly",
    # "etl",
    # "elt",
    # "pipeline",
    # "pipelines",
    "UNIX",
    "Linux",
    "MapReduce",
    "modelling",
    "warehouse",
    "warehousing",
    "mart",
    "lakes",
    "CI/CD",
    "Docker",
    "Git",
    "Jenkins",
    "Kubernetes",
    "Oracle",
    "Excel",
    "Cassandra",
    "Hevo",
    "Matillion",
    "Talend",
    "Pentaho",
    "InfoSphere",
    "DataStage",
    "Kafka",
    "Storm",
    "Flume",
    "Sqoop",
    "Wavefront",
    "Mahout",
    "Kafka",
    "Lambda",
    "Numpy",
    "Pandas",
    "Tableau",
    "Tibco",
    "Spotfire",
    "Blockchain",
    "Celery",
    # "cloud",
    "Weka",
    "Talend",
    "Informatica",
    "PowerCenter",
    "Stitch",
    "Hadoop",
    "Flink",
    "SAS",
    "SPSS",
    "OpenStack",
    "Openshift",
    "SSIS",
    "KNIME",
    "Kinesis",
    "Redis",
    "Cache",
    "Pub/Sub",
    "Qlik",
    "PyTorch",
    "batch",
    "HDFS",
    "ERP",
    "Panoply",
    "RDS",
    "C++",
    "Ruby",
    "go",
    "Power",
    "PowerBI",
]
