COUNTRIES = {
    "Portugal": {"country_code": "pt", "country_name": "Portugal"},
    "Poland": {"country_code": "pl", "country_name": "Poland"},
    "United Kingdom": {"country_code": "gb", "country_name": "United Kingdom"},
    "Spain": {"country_code": "es", "country_name": "Spain"},
    "France": {"country_code": "fr", "country_name": "France"},
    "Ireland": {"country_code": "ie", "country_name": "Ireland"},
    "Norway": {"country_code": "no", "country_name": "Norway"},
    "Sweden": {"country_code": "se", "country_name": "Sweden"},
    "Finland": {"country_code": "fi", "country_name": "Finland"},
    "Denmark": {"country_code": "dk", "country_name": "Denmark"},
    "Germany": {"country_code": "de", "country_name": "Germany"},
    "Belgium": {"country_code": "be", "country_name": "Belgium"},
    "Netherlands": {"country_code": "nl", "country_name": "Netherlands"},
    "Italy": {"country_code": "it", "country_name": "Italy"},
    "Austria": {"country_code": "at", "country_name": "Austria"},
    "Greece": {"country_code": "gr", "country_name": "Greece"},
    "Switzerland": {"country_code": "ch", "country_name": "Switzerland"},
    "Hungary": {"country_code": "hu", "country_name": "Hungary"},
    "Bulgaria": {"country_code": "bg", "country_name": "Bulgaria"},
    "Romania": {"country_code": "ro", "country_name": "Romania"},
    "Estonia": {"country_code": "ee", "country_name": "Estonia"},
    "Latvia": {"country_code": "lv", "country_name": "Latvia"},
    "Lithuania": {"country_code": "lt", "country_name": "Lithuania"},
    "Czech Republic": {"country_code": "cz", "country_name": "Czech Republic"},
    "Slovakia": {"country_code": "sk", "country_name": "Slovakia"},
    "Croatia": {"country_code": "hr", "country_name": "Croatia"},
}
