COUNTRIES = {
    "Portugal": {"country_code": "pt", "country_name": "Portugal"},
    "Poland": {"country_code": "pl", "country_name": "Poland"},
    "United Kingdom": {"country_code": "gb", "country_name": "United Kingdom"},
    "Spain": {"country_code": "es", "country_name": "Spain"},
    "France": {"country_code": "fr", "country_name": "France"},
    "Ireland": {"country_code": "ie", "country_name": "Ireland"},
    # "Norway",
    # "Sweden",
    # "Finland",
    "Denmark": {"country_code": "dk", "country_name": "Denmark"},
    "Germany": {"country_code": "de", "country_name": "Germany"},
    "Belgium": {"country_code": "be", "country_name": "Belgium"},
    "Netherlands": {"country_code": "nl", "country_name": "Netherlands"},
    "Italy": {"country_code": "it", "country_name": "Italy"},
    "Austria": {"country_code": "at", "country_name": "Austria"},
    "Greece": {"country_code": "gr", "country_name": "Greece"},
    "Switzerland": {"country_code": "ch", "country_name": "Switzerland"},
    # "Hungary",
    # "Bulgaria",
    # "Romania",
    # "Estonia",
    # "Latvia",
    # "Lithuania",
    # "Czechia",
    # "Slovakia",
    # "Croatia",
}
